version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: automarket
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health/" ]
      interval: 30s
      timeout: 3s
      retries: 3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/automarket
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

volumes:
  postgres-data: